import os
import re
import numpy as np
import cv2
from scipy.spatial import cKDTree
from detector_factory import *


def parse_ground_truth(file_path):
    """
    Parses the custom text output tables generated by Blender 2.92.
    Returns:
        dict: {(row, col): {"type": int, "coord": [x, y]}}
    """
    gt_data = {}
    if not os.path.exists(file_path):
        return gt_data
        
    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(",")
            r, c = int(parts[0]), int(parts[1])
            shape_type = int(parts[2])
            x_px, y_px = float(parts[3]), float(parts[4])
            gt_data[(r, c)] = {"type": shape_type, "coord": [x_px, y_px]}
            
    return gt_data

def evaluate_dynamic_topology(gt_dict, detected_dict, step_mm=20.0):
    """
    Evaluates tracking based on strict neighborhood constraints.
    A detection is rejected as a Ghost/Misalignment if it drifts 
    beyond 1/3 of the local pixel lattice spacing due to intense motion.
    """
    tp = 0   # True Positives: Correct ID matched within 1/3 lattice step
    ma = 0   # Misalignments: Wrong ID matched, or correct ID drifted > 1/3 step
    fp = 0   # Ghosts: Artifacts registered out in unmapped territory
    
    total_gt = len(gt_dict)
    if total_gt == 0:
        return 0, 0, 0, 0.0, 0.0

    # Extract ground truth structures for fast spatial mapping
    gt_keys = list(gt_dict.keys())
    gt_coords = np.array([gt_dict[k]["coord"] for k in gt_keys])
    gt_tree = cKDTree(gt_coords)

    for det_id, det_coord in detected_dict.items():
        # 1. Locate the closest ground truth node in pixel space
        dist, idx = gt_tree.query(det_coord, k=1)
        nearest_gt_key = gt_keys[idx]
        
        # 2. Dynamically calculate the local pixel step size
        # We query the nearest 2 neighbors to find the local lattice step in pixels
        # at this specific perspective compression area of the image.
        step_distances, _ = gt_tree.query(gt_coords[idx], k=2)
        local_pixel_step = step_distances[1] # Distance to the actual closest neighbor node
        
        # 3. Apply the 1/3 Lattice Step Hard Constraint Boundary
        max_allowed_drift_px = local_pixel_step / 3.0
        
        if dist > max_allowed_drift_px:
            # The point has drifted into no-man's land or crossed the neighbor threshold
            fp += 1 
            continue
            
        # 4. Fact of Classification Audit inside the valid 1/3 neighborhood
        if det_id == nearest_gt_key:
            tp += 1  # Successfully identified and localized within safety bounds
        else:
            ma += 1  # ID tracking mismatch inside the valid cell area

    # Strict performance metrics formulation
    precision_denom = tp + ma + fp
    precision = float(tp) / precision_denom if precision_denom > 0 else 0.0
    recall = float(tp) / total_gt if total_gt > 0 else 0.0
    
    return tp, ma, fp, precision, recall

def evaluate_pure_topology(gt_dict, detected_dict):
    """
    Evaluates pattern registration focusing entirely on classification accuracy.
    Uses KD-Tree spatial proximity mapping to catch mismatched topology IDs.
    """
    tp = 0   # True Positives: ID matched correctly on the closest spatial node
    ma = 0   # Misalignments: Nearest node belongs to a completely different ID
    fp = 0   # Ghosts: Extraneous nodes found out in blank background spaces
    
    total_gt = len(gt_dict)
    if total_gt == 0:
        return 0, 0, 0, 0.0, 0.0

    # Extract ground truth arrays for KD-Tree indexing
    gt_keys = list(gt_dict.keys())
    gt_coords = np.array([gt_dict[k]["coord"] for k in gt_keys])
    gt_tree = cKDTree(gt_coords)
    
    # Calculate a dynamic bounding threshold based on average node spacing 
    # to separate actual pattern real-estate from blank background spaces
    distances, _ = gt_tree.query(gt_coords, k=2)
    avg_node_spacing = np.mean(distances[:, 1])
    ghost_containment_threshold = avg_node_spacing * 0.75

    for det_id, det_coord in detected_dict.items():
        # Query nearest ground truth node point unconditionally
        dist, idx = gt_tree.query(det_coord, k=1)
        nearest_gt_key = gt_keys[idx]
        
        # 1. Is it out in empty space far away from the grid infrastructure?
        if dist > ghost_containment_threshold:
            fp += 1  # Registered a phantom point outside the pattern boundaries
            continue
            
        # 2. Fact of Classification Verification:
        if det_id == nearest_gt_key:
            tp += 1  # Correct topological identity assigned to the correct node space
        else:
            ma += 1  # Topological tracking error: Wrong ID assigned to this node area

    # Compute strict performance metrics using your exact formula specs
    precision_denom = tp + ma + fp
    precision = float(tp) / precision_denom if precision_denom > 0 else 0.0
    recall = float(tp) / total_gt if total_gt > 0 else 0.0
    
    return tp, ma, fp, precision, recall


# ==============================================================================
# MAIN TEST BED EXECUTION SUITE
# ==============================================================================
if __name__ == "__main__":

    args = parse_arguments()

    # 2. Global metric dimensions setup
    LATTICE_ROW_COUNT = args.rows
    LATTICE_COL_COUNT = args.cols
    detector = create_detector(args.engine, grid_rows = LATTICE_ROW_COUNT, grid_cols = LATTICE_COL_COUNT)
    
    DATASET_DIR = args.path
    if not os.path.exists(DATASET_DIR):
        print(f"Error: Target directory '{DATASET_DIR}' not found.")
        exit(1)
        
    files = os.listdir(DATASET_DIR)
    case_images = [f for f in files if f.startswith("case_") and f.endswith(".png")]
    case_images.sort()
    
    # Markdown Output Document Definition Block
    md_rows = [
        "| Test Case Name | GT Nodes | True Positives (TP) | Misalignments (MA) | Ghosts (FP) | Precision | Recall |",
        "| :--- | :---: | :---: | :---: | :---: | :---: | :---: |"
    ]
    
    print("Launching Topological Integrity Audit...")
    
    for img_name in case_images:
        case_id = re.sub(r"^case_", "", img_name)
        case_id = re.sub(r"\.png$", "", case_id)
        
        img_path = os.path.join(DATASET_DIR, img_name)
        gt_path = os.path.join(DATASET_DIR, f"case_{case_id}_gt.txt")
        
        if not os.path.exists(gt_path):
            continue
            
        image = cv2.imread(img_path)
        gt_map = parse_ground_truth(gt_path)
        
        # Run your tracking classification algorithm
        detected_map = detector.register_pattern(image)
        
        # Audit topology verification maps
        tp, ma, fp, prec, rec = evaluate_pure_topology(gt_map, detected_map)
        
        row_str = f"| {case_id} | {len(gt_map)} | {tp} | {ma} | {fp} | {prec:.4f} | {rec:.4f} |"
        md_rows.append(row_str)
        
    print("\n### TOPO-TRACKING PERFORMANCE RESULTS\n")
    print("\n".join(md_rows))
    print("\n")


