import numpy as np
import cv2
from scipy.spatial import cKDTree
from detector_factory import *


def parse_ground_truth(file_path):
    """
    Parses the custom text output tables generated by Blender 2.92.
    Returns:
        dict: {(row, col): (label, x, y)}
    """
    gt_data = {}
    if not os.path.exists(file_path):
        return gt_data
        
    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(",")
            r, c = int(parts[0]), int(parts[1])
            shape_type = int(parts[2])
            x_px, y_px = float(parts[3]), float(parts[4])
            gt_data[(r, c)] = (shape_type, x_px, y_px)
            
    return gt_data


def classify_topology_nodes(gt_dict, detected_dict, max_allowed_drift_px=None):
    """
    Analyzes and classifies each detected point based on geometric proximity constraints.
    Returns a dictionary mapping det_id to its point classification details.
    gt_dict: mapping of udeal points {(r,c): (type, x,y) }
    detected_dict: mapping of detected points {(r,c): (type, x,y) }
    """
    total_gt = len(gt_dict)
    if total_gt == 0 or len(detected_dict) == 0:
        return {}

    gt_keys = list(gt_dict.keys())
    gt_coords = np.array([gt_dict[k][1:3] for k in gt_keys])
    gt_tree = cKDTree(gt_coords)

    classifications = {}

    def is_isolated_point(key):
        return isinstance(key, int)

    for key, det_coord in detected_dict.items():
        coords_2d = det_coord[1:3]

        # 1. Spatial alignment query
        dist, idx = gt_tree.query(coords_2d, k=1)
        nearest_gt_key = gt_keys[idx]

        # 2. Dynamic neighborhood gate calculation
        if max_allowed_drift_px is None:
            step_distances, _ = gt_tree.query(gt_coords[idx], k=3)
            max_drift_px = (step_distances[1] + step_distances[2]) / 6.0
        else:
            max_drift_px = max_allowed_drift_px

        # 3. Classify detection result
        if key == nearest_gt_key:
            if dist > max_drift_px:
                pt_type = "ma"  # misalignment - Correct ID drifted too far
            else:
                pt_type = "tp"  # true positive - Perfect tracking hit
        else:
            if dist > max_drift_px:
                pt_type = "ghost"  # Arbitrary noise out in empty space
            elif is_isolated_point(key):
                pt_type = "solo"
            else:
                pt_type = "fp"  # Identity mismatch inside cell bounds

        classifications[key] = {
            "type": pt_type,
            "dist": float(dist),
            "coords": coords_2d,
            "nearest_gt": nearest_gt_key
        }

    return classifications


def compute_topology_statistics(gt_dict, classifications):
    """
    Aggregates point classifications to output a standardized performance metrics matrix.
    """
    stats = {"tp": 0, "ma": 0, "fp": 0, "ghost": 0, "solo": 0, "avg_dist": 0.0}

    total_gt = len(gt_dict)
    if total_gt == 0:
        return stats

    total_dist = 0.0
    max_dist = 0.0

    for node_info in classifications.values():
        pt_type = node_info["type"]
        stats[pt_type] += 1

        if pt_type == "tp":
            dist = node_info["dist"]
            total_dist += dist
            if max_dist < dist:
                max_dist = dist

    # Calculate average distance safely
    if stats["tp"] > 0:
        stats["avg_dist"] = total_dist / stats["tp"]
        stats["max_dist"] = max_dist
    else:
        stats["avg_dist"] = 0.
        stats["max_dist"] = 0.

    # Derive high-level analytics scores
    total_detections = len(classifications)
    stats["precision"] = float(stats["tp"]) / total_detections if total_detections > 0 else 0.0
    stats["recall"] = float(stats["tp"]) / total_gt if total_gt > 0 else 0.0
    stats["total_gt"] = total_gt

    return stats


# Create the palette dictionary exactly ONCE at the module level (static global constant)
_COLOR_PALETTE = {
    "gt": (120, 120, 120),      # Gray: Hollow background anchors
    "tp": (0, 255, 0),          # Bright Green: Perfect hits
    "fp": (0, 0, 255),          # wrong node assigned
    "ma": (0, 165, 255),        # Amber/Orange: Excessive drift
    "tn": (255, 0, 255),        # Bright Magenta: True Negative erasures
    "ghost": (0, 165, 255),     # Bright Red: phantoms
    "fn": (255, 0, 0),          # Bright blue: optical node miss
    "solo": (0, 120, 0),        # Isolated point in graph or misclassification
    "black": (0, 0, 0)
}

def _map_color(node_type: str) -> tuple:
    """
    Retrieves the BGR OpenCV color tuple from a pre-allocated static map.
    """
    return _COLOR_PALETTE.get(node_type, _COLOR_PALETTE["black"])


def draw_legend_overlay(frame: np.ndarray,
                        position: str = "bottom_left",
                        opacity: float = 0.75) -> np.ndarray:
    """
    Draws a semi-transparent background panel and color-coded telemetry legend
    at a user-specified corner quadrant on the video tracking frame canvas.

    Variables Description:
        frame (np.ndarray) : The image canvas matrix to receive the overlay.
        position (str)     : Screen quadrant position flag ("bottom_left",
                             "bottom_right", "top_left", "top_right").
        opacity (float)    : Transparency blending factor for the backdrop box.

    Returns:
        np.ndarray         : Canvas matrix with the embedded telemetry legend panel.
    """
    H_img, W_img = frame.shape[0], frame.shape[1]

    # 1. Define fixed dimension bounds for the legend panel window box
    panel_w = 420
    panel_h = 160
    margin_x = 20
    margin_y = 20

    # 2. Compute absolute pixel box limits dynamically based on position anchor
    pos_key = position.strip().lower()

    if pos_key == "top_left":
        x1 = margin_x
        y1 = margin_y
    elif pos_key == "top_right":
        x1 = W_img - panel_w - margin_x
        y1 = margin_y
    elif pos_key == "bottom_right":
        x1 = W_img - panel_w - margin_x
        y1 = H_img - panel_h - margin_y
    else:
        # Default fallback tracking context token: "bottom_left"
        x1 = margin_x
        y1 = H_img - panel_h - margin_y

    x2 = x1 + panel_w
    y2 = y1 + panel_h

    # 3. Render semi-transparent dark backdrop rectangle pane safely
    backdrop = np.copy(frame)
    cv2.rectangle(backdrop, (x1, y1), (x2, y2), (20, 20, 20), -1, lineType=cv2.LINE_AA)
    cv2.addWeighted(backdrop, opacity, frame, 1.0 - opacity, 0, frame)

    # Outer white perimeter hair-line border trim
    cv2.rectangle(frame, (x1, y1), (x2, y2), (180, 180, 180), 1, lineType=cv2.LINE_AA)

    # 4. Define structured legend item attributes (BGR color tuple, Label String)
    legend_items = [
        (_map_color("tp"), "True Positive (Perfect Decode Match)"),
        (_map_color("fp"), "False Positive (Index Alignment Drift)"),
        (_map_color("ma"), "Misalignment (Too high location drift) and Ghosts"),
        (_map_color("solo"), "Isolated lattice node"),
        (_map_color("fn"), "Optical Miss"),
        (_map_color("tn"), "True Negative (Expected Erasure)")
    ]

    # Text placement relative pointer calculations
    start_x = x1 + 20
    start_y = y1 + 25
    line_spacing = 26

    # 5. Stream tracking markers and label blocks straight onto the canvas sheet
    for idx, (color_bgr, label_text) in enumerate(legend_items):
        curr_y = start_y + (idx * line_spacing)

        # Render a matching indicator marker circle matching the overlay specs
        cv2.circle(frame, (start_x, curr_y - 4), 6, color_bgr, -1, lineType=cv2.LINE_AA)

        # Print the corresponding descriptive legend text block
        cv2.putText(frame,
                    label_text,
                    (start_x + 20, curr_y),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.40,
                    (240, 240, 240),
                    1,
                    cv2.LINE_AA)

    return frame


def draw_topology_scene(gt_dict, classifications, bgr_image, legend_position = None):
    """
    Renders the ground truth and classified nodes onto a canvas using OpenCV.
    Draws circles with high-contrast distinct colors.

    Parameters:
        gt_dict (dict): Ground truth node dictionary.
        classifications (dict): Output from classify_topology_nodes.
        bgr_image (np.ndarray): input image (e.g. your camera frame) to draw on.

    Returns:
        canvas (np.ndarray): BGR image matrix with rendered circles.
    """
    # 1. Initialize canvas (use your image frame if provided, otherwise clean black background)
    canvas = bgr_image.copy()

    # 3. Draw ground truth nodes as smaller hollow gray circles in the background
    if gt_dict:
        for v in gt_dict.values():
            # OpenCV requires integer coordinates for pixel plotting
            cx, cy = int(round(v[1])), int(round(v[2]))
            cv2.circle(canvas, (cx, cy), radius=4, color=_map_color("gt"), thickness=1)

    # 4. Overlay classified detection nodes as solid filled circles
    for node_info in classifications.values():
        pt_type = node_info["type"]
        x, y = node_info["coords"]
        cx, cy = int(round(x)), int(round(y))
        # Draw solid circle (thickness=-1 fills the circle completely)
        cv2.circle(canvas, (cx, cy), radius=7, color=_map_color(pt_type), thickness=-1)

    if legend_position is not None:
        draw_legend_overlay(
            frame=canvas,
            position=legend_position,
            opacity=0.8
        )

    return canvas


def compute_detection_statistics(label_status):
    if label_status is None:
        return 0, 0, 0
    misclassified = np.count_nonzero(label_status == detector.MISCLASSIFIED)
    ghosts = np.count_nonzero(label_status == detector.GHOST)
    return misclassified, ghosts


# ==============================================================================
# VALIDATION EXECUTION SUITE
# ==============================================================================
if __name__ == "__main__":
    # -p blender_output_asymmetric_circles -e asymmetric_circles -r 30 -c 31
    # -p blender_output_hexagonal
    args = parse_arguments()
    LATTICE_ROW_COUNT = args.rows
    LATTICE_COL_COUNT = args.cols
    detector = create_detector(args.engine, grid_rows = LATTICE_ROW_COUNT, grid_cols = LATTICE_COL_COUNT)
    
    DATASET_DIR = args.path
    if not os.path.exists(DATASET_DIR):
        print(f"Error: Target directory '{DATASET_DIR}' not found.")
        exit(1)
        
    files = os.listdir(DATASET_DIR)
    case_images = [f for f in files if f.endswith(".png")]
    case_images.sort()
    debug_output = True

    print("Launching Topological Integrity Audit...")

    with open(os.path.join(DATASET_DIR, "summary.md"), 'w', encoding='ascii') as f:
        f.write("\n### TOPOLOGICAL MATCHING PERFORMANCE RESULT\n\n")
        f.write("| Test Case Name | GT Nodes | Total Detected | Misclassified | False detection |"
                " TP | Misalignments (MA) | FP | Skip | Precision | Recall | Avg Dist (pixels) |Max Dist (pixels) |\n")
        f.write("| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |\n")
        for img_name in case_images:
            case_id = img_name[:-4]
            img_path = os.path.join(DATASET_DIR, img_name)
            gt_path = os.path.join(DATASET_DIR, case_id + "_gt.txt")

            if not os.path.exists(gt_path):
                continue
            print(f"Processing test case {case_id}...")

            image = cv2.imread(img_path)
            stat_image = image.copy()
            gt_map = parse_ground_truth(gt_path)
            detected_result = detector.register_pattern(image, debug_output)
            cv2.imwrite(os.path.join(DATASET_DIR, img_name + "-debug.png"), image)
            detected_map = {}
            verified = []
            if "topological_matrix" in detected_result:
                points = detected_result.get("points")
                topological_matrix = detected_result.get("topological_matrix")
                labels = detected_result.get("label_status")
                h, w = topological_matrix.shape
                matched_point_indexes = set()
                for r in range(h):
                    for c in range(w):
                        point_idx = topological_matrix[r, c]
                        if point_idx >= 0:
                            x, y = points[point_idx]
                            detected_map[(r,c)] = (labels[point_idx], x, y)
                            matched_point_indexes.add(point_idx)
                for point_idx, point in enumerate(points):
                    if point_idx not in matched_point_indexes:
                        x, y = point
                        detected_map[point_idx] = (labels[point_idx], x, y)

            # topology verification maps
            classifications = classify_topology_nodes(gt_map, detected_map)
            output_image = draw_topology_scene(gt_map, classifications, stat_image, "bottom_left")
            cv2.imwrite(os.path.join(DATASET_DIR, img_name + "-stat.png"), output_image)
            misclassified, unmatched =\
                compute_detection_statistics(detected_result.get("label_status"))
            metrics = compute_topology_statistics(gt_map, classifications)
            # Strict performance metrics formulation
            # --- EXTACT AND FORMAT METRIC VECTOR CONSTRAINTS ---
            tp = metrics["tp"]
            ma = metrics["ma"]
            fp = metrics["fp"]

            # Enforce your strict conservation invariant check
            assert unmatched == metrics["ghost"] + metrics["solo"]
            skips = metrics["solo"]
            ghosts = metrics["ghost"]

            total = tp + ma + fp
            precision = tp / total if total > 0 else 0.0
            recall = tp / len(gt_map) if len(gt_map) > 0 else 0.0

            dist = metrics['avg_dist']
            max_dist = metrics['max_dist']

            # --- STREAMLINED ROW WRITER ---
            # Outputs clean independent metrics without double-counting columns
            f.write(
                f"| {case_id} | {len(gt_map)} | {len(labels)} | {misclassified} | {ghosts} | "
                f"{tp} | {ma} | {fp} | {skips} | {precision:.3f} | {recall:.3f} | "
                f"{dist:.1f} | {max_dist:.1f} |\n"
            )

        # --- RIGOROUS ACADEMIC FOOTNOTE SECTION ---
        f.write("\n***\n")
        f.write("### Definitions\n\n")
        f.write("\n***\n")
        f.write(
            "* **$\\text{Misclassified (Corrected)}$:** Tracks the number of physical nodes whose binary shape labels "
            "(circles vs. triangles) were initially misidentified by the low-level detector, "
            "but were **successfully resolved and corrected** by the decoder. They are fully included in the $TP$ pool.\n"
        )
        f.write(
            "* **$\\text{False Detection (Ghost)}$:** Pure background raster noise or glare reflections erroneously "
            "picked up by the sensor but blocked from entering the lattice by the topological filter. They are discarded from further processing.\n"
        )
        f.write(
            "* **$\\text{Skip}$ (Isolated Nodes):** Valid physical grid features that were successfully detected on the sensor "
            "but left with a graph adjacency degree of zero because surrounding marker dropouts prevented "
            "them from anchoring to a major topological island. They are discarded from further processing.\n"
        )
        f.write(
            "* All evaluation ratio bounds follow standard photogrammetric confusion matrix principles:\n"
            "  $$\\text{Precision} = \\frac{TP}{TP + FP + MA}$$\n"
            "  $$\\text{Recall} = \\frac{TP}{\\text{Total Visible GT Nodes}}$$\n"
        )

        f.write(f"\n***\n*Generated automatically by {HexagonalTopologyDetector.ENGINE_FULL_NAME}*")
        f.write("\n")
        print("Processing completed")

