name: Run Code Unit Tests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Unit Tests
        run: |
          python m_sequence.py
          python lattice_topology.py
          python matcher.py
          python crystal.py
          python camera.py

      - name: Execute Calibration Test Bench
        run: |
          python pattern_decoder_test.py

      - name: Upload Calibration Summary Report
        uses: actions/upload-artifact@v4
        with:
            name: calibration-summary-metrics
            path: ./output/summary_report.md
            archive: false
            overwrite: true
            
